#!/usr/bin/perl -w

# A tool for extracting sequence records from a fasta file

#================================================================
# Format fasta output string
sub to_fasta {
        my ($seq_name, $seq, $len) = @_;

	# default to 80 characters of sequence per line
        $len = 60 unless $len;

        my $formatted_seq = ">$seq_name\n";
        while (my $chunk = substr($seq, 0, $len, "")) {
                $formatted_seq .= "$chunk\n";
        }
        
        return $formatted_seq;
}
#======================INPUT==========================================
# Read input data
# Creates an array for storing fasta: id (key) to sequence (value)
my %fas_data;
# Check if a fasta file is given as an argument if yes open it and read it ELSE read from standard input


my @requests;


# Read in data from STDIN
while (<>) {
    # Skipp empty lines
    next if /^$/;
    # Check if it's an id line
    if (/>(.*)/) {
        # Store curent id in $seq_name
        $seq_name = $1;
    } else {
        # if not an id check if there is a current id defined else throw an error
        unless (defined $seq_name) {
            print "Format error! Check the file!\n";
            last;
        }
        # remove newline characters
	s/\R//g;
        # read in sequence and append it to the current sequence
        $fas_data{$seq_name} .= $_;
    }    
}
#======================OUTPUT================================================================
for (sort keys %fas_data) {
    my $id = $_;

    my $i = 0;
    my @fragments = split /N+/, $fas_data{$id};

    for (@fragments) {
	$i++;
        print &to_fasta("$id\_contig_$i", $_);
        
    }
    
}
