#!/usr/bin/perl -w
# This programs sort sequence records in alphabetical order

sub to_fasta {
        my ($seq_name, $seq, $len) = @_;

	# default to 80 characters of sequence per line
        $len = 80 unless $len;

        my $formatted_seq = ">$seq_name\n";
        while (my $chunk = substr($seq, 0, $len, "")) {
                $formatted_seq .= "$chunk\n";
        }
        
        return $formatted_seq;
}

my %fas_data;

while (<>) {
    next if /^$/;
    if (/>(.*)/) {
        $seq_name = $1;
    } else {
        unless (defined $seq_name) {
            print "Format error! Check the file!\n";
            last;
        }
        chomp;
        $fas_data{$seq_name} .= $_;
    }    
}

for (sort keys %fas_data) {
    print &to_fasta($_, $fas_data{$_});
}
